# Generated by Django 3.1.2 on 2020-11-21 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField()),
                ('customer_age', models.SmallIntegerField()),
                ('customer_citizenship', models.CharField(max_length=255)),
                ('customer_passportnum', models.CharField(max_length=255)),
                ('customer_email', models.CharField(max_length=255)),
                ('customer_phone_num', models.CharField(max_length=255)),
                ('customer_licence_num', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_category', models.SmallIntegerField(unique=True)),
                ('driver_name', models.CharField(max_length=255, unique=True)),
                ('driver_email', models.CharField(max_length=255, unique=True)),
                ('driver_phone_num', models.CharField(max_length=255, unique=True)),
                ('english_speaking', models.BooleanField(blank=True, null=True)),
                ('works_from_date', models.DateField(blank=True, null=True)),
                ('driving_experience_in_years', models.SmallIntegerField(blank=True, null=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('pic_path', models.FileField(upload_to='pic_path')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('payment_status', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status_description', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialEquipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_description', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(max_length=255)),
                ('pic_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfVehicle',
            fields=[
                ('vehicle_type', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type_description', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(db_column='vehicle_Id', primary_key=True, serialize=False)),
                ('vehicle_brand', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('vehicle_regnum', models.CharField(max_length=255)),
                ('pic_path', models.CharField(blank=True, max_length=500, null=True)),
                ('vehicle_type', models.ForeignKey(db_column='vehicle_type', on_delete=django.db.models.deletion.DO_NOTHING, to='RentCar.typeofvehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rent_id', models.AutoField(primary_key=True, serialize=False)),
                ('rent_fromdate', models.DateField()),
                ('rent_todate', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentCar.customers')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentCar.driver')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentCar.specialequipment')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='RentCar.payment')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RentCar.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.ForeignKey(db_column='payment_status', on_delete=django.db.models.fields.CharField, to='RentCar.paymentstatus'),
        ),
    ]
