# Generated by Django 3.1.2 on 2021-02-16 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField()),
                ('customer_age', models.SmallIntegerField()),
                ('customer_citizenship', models.CharField(max_length=255)),
                ('customer_passportnum', models.CharField(max_length=255)),
                ('customer_email', models.CharField(max_length=255)),
                ('customer_phone_num', models.CharField(max_length=255)),
                ('customer_licence_num', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_category', models.SmallIntegerField(unique=True)),
                ('driver_name', models.CharField(max_length=255, unique=True)),
                ('driver_email', models.CharField(max_length=255, unique=True)),
                ('driver_phone_num', models.CharField(max_length=255, unique=True)),
                ('english_speaking', models.BooleanField(blank=True, null=True)),
                ('works_from_date', models.DateField(blank=True, null=True)),
                ('driving_experience_in_years', models.SmallIntegerField(blank=True, null=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('pic_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('payment_status', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status_description', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Payment_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('rent_id', models.AutoField(primary_key=True, serialize=False)),
                ('rent_fromdate', models.DateField()),
                ('rent_todate', models.DateField()),
            ],
            options={
                'db_table': 'Rent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialEquipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_description', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(max_length=255)),
                ('pic_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Special_equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfVehicle',
            fields=[
                ('vehicle_type', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type_description', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Type_of_vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(db_column='vehicle_Id', primary_key=True, serialize=False)),
                ('vehicle_brand', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('vehicle_regnum', models.CharField(max_length=255)),
                ('pic_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=2)),
                ('citizenship', models.CharField(max_length=20)),
                ('passportnum', models.CharField(max_length=10)),
                ('adress', models.TextField()),
                ('phone_num', models.CharField(max_length=10)),
                ('license_num', models.CharField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
