# Generated by Django 3.1.2 on 2021-02-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentCar', '0002_auto_20210216_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='age',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='adress',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='citizenship',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='license_num',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='passportnum',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone_num',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
